const journalingQuestions = [
    "What are three things I'm grateful for today, and why do they hold significance in my life?",
    "What challenges or obstacles did I face today, and how did I navigate through them? What did I learn from these experiences?",
    "What are my short-term and long-term goals, and what steps can I take tomorrow to move closer to achieving them?",
    "How did I take care of my physical, emotional, and mental well-being today? Is there something I can improve or prioritize tomorrow?",
    "What moments or interactions brought me joy, and how can I invite more of these positive experiences into my life?",
    "What self-limiting beliefs or negative thought patterns surfaced today, and how can I reframe them to be more empowering?",
    "How did I express creativity or engage in activities that bring me a sense of fulfillment? How can I continue nurturing my creative side?",
    "Did I connect with someone on a deeper level today? How can I cultivate and strengthen my relationships with others?",
    "What new insights or lessons did I gain about myself or the world around me today?",
    "If I could give my future self advice based on today's experiences, what would it be? What wisdom can I impart to help guide my future decisions?",
    "What is one thing that made me smile today?",
    "What is a small step I can take tomorrow to work towards a larger goal?",
    "What is a favorite childhood memory that brings me happiness?",
    "What is a book, movie, or song that has deeply resonated with me recently?",
    "What is a place I've always wanted to visit and why?",
    "What is an act of kindness I witnessed or performed today?",
    "What is something I've been avoiding that I can confront and address?",
    "What is a skill or hobby I would like to develop further?",
    "What is a life lesson I've learned from a past mistake?",
    "What is an area of my life where I can practice more self-compassion?",
    "What is a quote that inspires and motivates me?",
    "What is an activity that helps me unwind and relax?",
    "What is a fear or worry that I can challenge and overcome?",
    "What is a positive affirmation or mantra that resonates with me?",
    "What is a relationship in my life that I am grateful for?",
    "What is a goal I've achieved in the past that I'm proud of?",
    "What is a decision I made today that aligned with my values?",
    "What is something I've learned from a recent failure?",
    "What is a dream or aspiration I've been hesitant to pursue?",
    "What is a quality in myself that I appreciate and value?",
    "What is a lesson I've learned from a difficult experience?",
    "What is a way I can show kindness and compassion to myself?",
    "What is a moment when I felt truly alive and present?",
    "What is a place in nature that brings me peace and tranquility?",
    "What is a strength or talent that I can leverage to achieve my goals?",
    "What is a new habit I can start to improve my daily routine?",
    "What is a person who has positively impacted my life, and why?",
    "What is a decision I made today that I can learn from?",
    "What is a dream or goal that I've set for the future?",
    "What is a place I've visited that holds special memories for me?",
    "What is an experience that has shaped my perspective on life?",
    "What is a situation that challenged me and helped me grow?",
    "What is an achievement that I'm proud of from this past year?",
    "What is a way I can give back to my community?",
    "What is a thought pattern I can work on shifting?",
    "What is a lesson I've learned from a recent success?",
    "What is a meaningful ritual or routine in my daily life?",
    "What is a person who inspires me to be a better version of myself?",
    "What is a goal that scares me but excites me at the same time?"
];
  
export default journalingQuestions;
  